### ISSUE TITLE
Lacking 'enable for this scene' menu option

### ISSUE THREAD

**Issue by Wokeye27** [erithtotl/FVTT-Wall-Height#1] opened 2021-02-13 04:05 UTC
Hi, 
The latest versions appear to have disabled wall heights on my walls on existing scenes, and does not appear as an option on new scenes.  
There is a space in the UI for the 'Enable on this scene' tickbox as shown in the screenshots but it doesn't appear for me.  
![image](https://user-images.githubusercontent.com/77101610/107841148-a9101b00-6e0c-11eb-95df-3a064d3dfef6.png)

I have the latest versions of Foundry, 5E and the module installed.

**Comment by Tristan-Goucher** [comment] 2021-02-13 08:43
I can confirm this in PF1E as well. There's an error in the loading of Wall Heights and getting it set up with libWrapper:

Failed to load resource: http://localhost:25564/modules/wall-height/libwrapper/shim/shim.js. the server responded with a status of 404 (Not Found)

**Comment by Gedfort** [comment] 2021-02-13 13:47
Can't seem to use the module either, just updated the module right before as well, but the problem was there also before I updated, however not a few days ago...

**Comment by FatBiscuit** [comment] 2021-02-13 16:07
This WAS working for me a few days ago.  It seems the latest update has removed all mentions of the module from my scenes...

**Comment by erithtotl** [comment] 2021-02-13 18:26
Sorry guys, I had used submodules in git to pull in the libwrapper shim, not realizing it would not get included in the package.  Should be fixed with latest release.

**Closed by erithtotl** 2021-02-13 18:26 UTC
